site_name: relMUSS
theme:
    name: readthedocs
markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
nav:
    - About: 'index.md'
    - Specification: 
        - 'Basic tags': 'basic.md'
        - 'Specific tags': 'attributes.md'
        - 'Lists for referencing': 'referencing'
    - Workflow: 'workflow.md'
    
    

