[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "relMUSS"
authors = [{name = "Theo Pleizier", email = "t.t.j.pleizier@pthu.nl"}]
dynamic = ["version", "description"]
